        'image' => '/public/chromadb.png',
        'src' => '/public/discord.svg',
        'src' => '/public/facebook.svg',
        'src' => '/public/instagram.svg',
        'image' => '/public/html.png',
        'image' => '/public/css.png',
        'image' => '/public/js.png',
        'image' => '/public/tailwind.png',
        'image' => '/public/ts.png',
        'image' => '/public/next.png',
        'image' => '/public/mysql.png',
        'image' => '/public/graphql.png',
        'image' => '/public/flask-logo.png',
        'image' => '/public/python.png',
        'image' => '/public/docker.webp',
        'image' => '/public/kubernetes.png',
        'image' => '/public/figma.png',
        'image' => '/public/c.png',
        'image' => '/public/cpp.png',
        'image' => '/public/java.png',
        'image' => '/public/scala.png',
        'image' => '/public/sqlalchemy-logo.png',
        'image' => '/public/scikit-learn.png',
my-logo.png',
g',
',
,
',
s.png',
bp',
g',
o.png',
ng',
',
,
png',
,

